### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by szakarias** [passsy/flutterw_sidekick_plugin#2]
Thanks for adding topics to your package!

Due to a bug, we were not validating the names on package upload. This has been fixed and will be enforced when publishing a new version.

The guidelines for choosing topic names is https://dart.dev/tools/pub/pubspec#topics. Concretely we do not allow underscores.

Could you please update your topics names in the pubspec?

Thanks in advance and sorry for the inconvenience.

**Comment by passsy** [comment]
Sorry Sarah, overlooked this issue
